### PR TITLE
Better threadmark redirect

### LINKED ISSUE #20: Threadmarker disappears after editing a threadmarked post
To reproduce:

1) Threadmark a post
2) Edit it and save

Updated post is re-rendered but the threadmarker is not. This only affects the user editing the post.

Refreshing the page shows the threadmaker again.

### PR DESCRIPTION
**Pull request by sidane**
Fixes #20 and #21.

Seem reasonable @Xon?

### CODE REVIEW

**Comment by Xon** [comment]
Looks good!

**Comment by Xon** [comment]
Testing shows the post isn't visually duplicated. But the threadmark is.

example

**Comment by Xon** [comment]
On testing, the issue is the threadmark is outside the li block the entire post is in.

XF doesn't know it needs to remove the threadmark block when removing the old post and adding the new one via JS.

**Comment by sidane** [comment]
Hmm, not seeing that issue when I test it. Editing a post replaces the existing `#post-<id>` element with the newly edited version. As the threadmark is outside of that element, it shouldn't change.

Could this be your fork having have other changes that are not in `master` / this pull request?

**Comment by Xon** [comment]
Yes, I realised that it is likely the result of including the threadmark data as part of the post in the fetch-with-post branch. So please ignore the comments about this PR

**Comment by sidane** [comment]
Superseded by #28.

**Pull request closed without merging**
