### PR TITLE
Sortable threadmarks

### PR DESCRIPTION
**Pull request by Xon**
Sortable threadmarks.
- Moves threadmark rebuilding in-line with the thread.
- Ensures a lack of name collision between threadmark properties and post properties
- Records/displays who created a threadmark.
- Threadmark preview on next/previous links.
- Missed branch which ensures Elastic Search schema is up-to-date where possible (reduces the amount of data stored)

### CODE REVIEW

**Comment by Xon** [comment]
@sidane any chance you can look at this?

**Comment by sidane** [comment]
Hi @Xon, I'll take a look at this tomorrow. Apologies again for the delay.

**Comment by sidane** [comment]
Apologies @Xon, it won't be today, a bunch of stuff has come up. Hopefully in the next few days.

**Comment by Xon** [comment]
@sidane do you have any objections to me releasing my own fork on XenForo.com's resource manager or taking over the resource in xenforo's resource manager?

**Comment by Xon** [comment]
I will be deploying this exact rebased version to SB/SV and doing final testing on it

**Comment by Xon** [comment]
@sidane fyi I've pushed a release for v1.2.0 

This code has been used for quite some time on two busy sites and represents a massive improvement over the previous release of v1.1.5

Could you release this on XenForo.com's resource manager?

**Pull request merged**
